### PR TITLE
build: change directory to the project directory when running the hooks

### PR DESCRIPTION
**Pull request by FFY00**
Signed-off-by: Filipe Laíns <lains@archlinux.org>

### CODE REVIEW

**Comment by FFY00** [comment]
@uranusjr does this fix #68 for you?

**Comment by FFY00** [comment]
Uh, @gaborbernat can you look at this?

**Review by gaborbernat — APPROVED** [review]

**Comment by gaborbernat** [comment]
Looks ok, but fix the CI.

**Comment by FFY00** [comment]
Do you know what is wrong? I don't use macos.

**Comment by FFY00** [comment]
Nevermind, looks like `/private/var` is a symlink to `/var`.

**Review by gaborbernat — CHANGES_REQUESTED** [review]
Tests are still failing 😢

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
