### PR TITLE
pre-commit: add double-quote-string-fixer

### PR DESCRIPTION
**Pull request by FFY00**
Signed-off-by: Filipe Laíns <lains@archlinux.org>

### CODE REVIEW

**Review by gaborbernat — COMMENTED** [review]
Before we merge this, let's settle the question of to black or not to black. Because if to black, then this commit is not needed...

**Comment by FFY00** [comment]
If we are ever to move to black, I'd like it to be with `-S` and keep the single quotes.

**Comment by gaborbernat** [comment]
> If we are ever to move to black, I'd like it to be with `-S` and keep the single quotes.

Ever the rebellious, I see. So the ever question is now? Yay or nay? From my side, and Paul's side +1 AFAIK.

**Review by gaborbernat — APPROVED** [review]
maser is broken because of https://foss.heptapod.net/pypy/pypy/-/issues/3321, we should probably work around the issue or disable the test for it...

**Pull request merged**
