### PR TITLE
Add support for Python 3.9

### PR DESCRIPTION
**Pull request by gaborbernat**
future is here

### CODE REVIEW

**Comment by gaborbernat** [comment]
So the venv creation fails under Windows 3.9 with:

```
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'C:\Users\traveler\git\python-build\.tox\py39\Scripts\python.exe'
  isolated = 1
  environment = 0
  user site = 0
  import site = 1
  sys._base_executable = 'C:\\Users\\traveler\\git\\python-build\\.tox\\py39\\Scripts\\python.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\Users\\traveler\\AppData\\Local\\Temp\\build-env-fly1zio8\\Scripts\\python.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\Users\\traveler\\git\\python-build\\.tox\\py39\\Scripts\\python39.zip',
    '.\\DLLs',
    '.\\lib',
    'C:\\Users\\traveler\\git\\python-build\\.tox\\py39\\Scripts',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001184 (most recent call first):
<no Python frame>
```

**Comment by gaborbernat** [comment]
So seems the issue is calling venv module from within virtualenv. Will need to investigate more.

**Comment by gaborbernat** [comment]
Tracked it down to this core https://bugs.python.org/issue42013 bug.

**Comment by gaborbernat** [comment]
@FFY00 this now passes 👍 fixed via https://virtualenv.pypa.io/en/latest/changelog.html#v20-0-34-2020-10-12

**Review by FFY00 — APPROVED** [review]
:tada:

**Pull request merged**
